# Generated by Django 5.2.4 on 2025-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0002_instructorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
