# Generated by Django 5.2.4 on 2025-07-25 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('rz_order_id', models.CharField(max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('course_objects', models.ManyToManyField(related_name='course_orders', to='instructorApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
